package com.asaad27.ui.theme

import androidx.compose.ui.graphics.Color

val darkPurple_light_primary = Color(0xFF6750A4)
val white_light_onPrimary = Color(0xFFFFFFFF)
val lightPurple_light_primaryContainer = Color(0xFFEADDFF)
val deepPurple_light_onPrimaryContainer = Color(0xFF21005D)
val grayishPurple_light_secondary = Color(0xFF625B71)
val white_light_onSecondary = Color(0xFFFFFFFF)
val lightLavender_light_secondaryContainer = Color(0xFFE8DEF8)
val darkGrayishPurple_light_onSecondaryContainer = Color(0xFF1D192B)
val mutedRed_light_tertiary = Color(0xFF7D5260)
val white_light_onTertiary = Color(0xFFFFFFFF)
val pink_light_tertiaryContainer = Color(0xFFFFD8E4)
val darkRed_light_onTertiaryContainer = Color(0xFF31111D)
val red_light_error = Color(0xFFB3261E)
val white_light_onError = Color(0xFFFFFFFF)
val lightRed_light_errorContainer = Color(0xFFF9DEDC)
val darkRed_light_onErrorContainer = Color(0xFF410E0B)
val gray_light_outline = Color(0xFF79747E)
val offWhite_light_background = Color(0xFFFFFBFE)
val darkGray_light_onBackground = Color(0xFF1C1B1F)
val offWhite_light_surface = Color(0xFFFFFBFE)
val darkGray_light_onSurface = Color(0xFF1C1B1F)
val lightGray_light_surfaceVariant = Color(0xFFE7E0EC)
val darkGray_light_onSurfaceVariant = Color(0xFF49454F)
val darkGray_light_inverseSurface = Color(0xFF313033)
val lightGray_light_inverseOnSurface = Color(0xFFF4EFF4)
val lightPurple_light_inversePrimary = Color(0xFFD0BCFF)
val black_light_shadow = Color(0xFF000000)
val darkPurple_light_surfaceTint = Color(0xFF6750A4)
val grayishLavender_light_outlineVariant = Color(0xFFCAC4D0)
val black_light_scrim = Color(0xFF000000)


val lightPurple_dark_primary = Color(0xFFD0BCFF)
val darkPurple_dark_onPrimary = Color(0xFF381E72)
val mediumPurple_dark_primaryContainer = Color(0xFF4F378B)
val lightPurple_dark_onPrimaryContainer = Color(0xFFEADDFF)
val lightLavender_dark_secondary = Color(0xFFCCC2DC)
val darkGrayishPurple_dark_onSecondary = Color(0xFF332D41)
val darkLavender_dark_secondaryContainer = Color(0xFF4A4458)
val lightLavender_dark_onSecondaryContainer = Color(0xFFE8DEF8)
val lightPink_dark_tertiary = Color(0xFFEFB8C8)
val darkRed_dark_onTertiary = Color(0xFF492532)
val darkPink_dark_tertiaryContainer = Color(0xFF633B48)
val pink_dark_onTertiaryContainer = Color(0xFFFFD8E4)
val lightRed_dark_error = Color(0xFFF2B8B5)
val darkRed_dark_onError = Color(0xFF601410)
val red_dark_errorContainer = Color(0xFF8C1D18)
val lightRed_dark_onErrorContainer = Color(0xFFF9DEDC)
val lightGray_dark_outline = Color(0xFF938F99)
val darkGray_dark_background = Color(0xFF1C1B1F)
val lightGray_dark_onBackground = Color(0xFFE6E1E5)
val darkGray_dark_surface = Color(0xFF1C1B1F)
val lightGray_dark_onSurface = Color(0xFFE6E1E5)
val darkGray_dark_surfaceVariant = Color(0xFF49454F)
val lightGray_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val lightGray_dark_inverseSurface = Color(0xFFE6E1E5)
val darkGray_dark_inverseOnSurface = Color(0xFF313033)
val darkPurple_dark_inversePrimary = Color(0xFF6750A4)
val black_dark_shadow = Color(0xFF000000)
val lightPurple_dark_surfaceTint = Color(0xFFD0BCFF)
val darkGray_dark_outlineVariant = Color(0xFF49454F)
val black_dark_scrim = Color(0xFF000000)



val seed = Color(0xFF6750A4)
